name: Windows MSI Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      shell: bash
      run: |
        mkdir -p build/packages
        if [ ! -f License.rtf ]; then
          echo "{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset0 Calibri;}}\viewkind4\uc1\pard\f0\fs22 MIT License\par }" > License.rtf
        fi

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset --yes
        echo "WiX installed successfully"
        where candle || echo "candle not found"
        where light || echo "light not found"

    - name: Install SFML dependencies
      run: |
        choco install sfml --yes

    - name: Configure project
      shell: bash
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      shell: bash
      run: |
        cmake --build build --config Release --parallel 4

    - name: Generate MSI package
      shell: bash
      run: |
        cd build
        cpack -G "WIX" --verbose
        find . -name "*.msi" -exec cp {} packages/ \;

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-msi-package
        path: build/packages/
        retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Windows release includes:
          - MSI installer package
        draft: false
        prerelease: false
        files: |
          artifacts/windows-msi-package/*.msi
        token: ${{ secrets.GITHUB_TOKEN }}
