name: Windows MSI Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      shell: bash
      run: |
        mkdir -p build/packages
        if [ ! -f License.rtf ]; then
          echo "{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset0 Calibri;}}\viewkind4\uc1\pard\f0\fs22 MIT License\par }" > License.rtf
        fi

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset --yes
        echo "WiX installed successfully"

    - name: Download and extract SFML
      shell: bash
      run: |
        curl -L -o sfml.zip https://www.sfml-dev.org/files/SFML-2.6.1-windows-vc17-64-bit.zip
        7z x sfml.zip -o"C:/sfml"
        echo "SFML_DIR=C:/sfml/SFML-2.6.1" >> $GITHUB_ENV

    - name: Configure project
      shell: bash
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DSFML_DIR="${{ env.SFML_DIR }}"

    - name: Build project
      shell: bash
      run: |
        cmake --build build --config Release --parallel 4

    - name: Install files to package directory
      shell: bash
      run: |
        mkdir -p build/install
        cp build/Release/doodle_jump.exe build/install/
        cp -r images build/install/
        cp "C:/sfml/SFML-2.6.1/bin/"*.dll build/install/

    - name: Generate MSI package
      shell: bash
      run: |
        cd build
        cpack -G WIX --verbose \
          -D CPACK_PACKAGE_NAME="DoodleJump" \
          -D CPACK_PACKAGE_VENDOR="YourCompany" \
          -D CPACK_PACKAGE_VERSION="1.0.0" \
          -D CPACK_WIX_PRODUCT_GUID="$(powershell -command "[guid]::NewGuid().ToString()")" \
          -D CPACK_WIX_UPGRADE_GUID="$(powershell -command "[guid]::NewGuid().ToString()")" \
          -D CPACK_PACKAGE_INSTALL_DIRECTORY="DoodleJump" \
          -D CPACK_INSTALL_CMAKE_PROJECTS="$(pwd);DoodleJump;ALL;/" \
          -D CPACK_INSTALL_COMMANDS="echo 'Using pre-installed files'" \
          -D CPACK_INSTALLED_DIRECTORIES="install;DoodleJump"
        
        find . -name "*.msi" -exec cp {} packages/ \;

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-msi-package
        path: build/packages/
        retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Windows release includes:
          - MSI installer package
        draft: false
        prerelease: false
        files: |
          artifacts/windows-msi-package/*.msi
        token: ${{ secrets.GITHUB_TOKEN }}
