name: Windows MSI Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      shell: bash
      run: |
        mkdir -p build/packages
        if [ ! -f License.rtf ]; then
          echo "{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset0 Calibri;}}\viewkind4\uc1\pard\f0\fs22 MIT License\par }" > License.rtf
        fi

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset --yes
        echo "WiX installed successfully"

    - name: Download and extract SFML
      shell: bash
      run: |
        curl -L -o sfml.zip https://www.sfml-dev.org/files/SFML-2.6.1-windows-vc17-64-bit.zip
        7z x sfml.zip -o"C:/sfml"
        echo "SFML_DIR=C:/sfml/SFML-2.6.1" >> $GITHUB_ENV

    - name: Configure project
      shell: bash
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DSFML_DIR="${{ env.SFML_DIR }}"

    - name: Build project
      shell: bash
      run: |
        cmake --build build --config Release --parallel 4

    - name: Prepare installation files
      shell: bash
      run: |
        mkdir -p build/install
        # Копируем исполняемый файл
        cp build/Release/doodle_jump.exe build/install/
        # Копируем ресурсы
        cp -r images build/install/
        # Копируем необходимые DLL из SFML
        cp "C:/sfml/SFML-2.6.1/bin/"*.dll build/install/

    - name: Generate WXS file manually
      shell: bash
      run: |
        cd build
        cat > install.wxs << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="DoodleJump" Language="1033" Version="1.0.0" Manufacturer="YourCompany" UpgradeCode="$(powershell -command "[guid]::NewGuid().ToString()")">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine"/>
            <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
            <MediaTemplate />
            
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="DoodleJump" />
              </Directory>
            </Directory>
            
            <DirectoryRef Id="INSTALLFOLDER">
              <Component Id="MainExecutable" Guid="$(powershell -command "[guid]::NewGuid().ToString()")">
                <File Id="doodle_jump.exe" Source="install/doodle_jump.exe" KeyPath="yes" Checksum="yes"/>
              </Component>
              <Component Id="Images" Guid="$(powershell -command "[guid]::NewGuid().ToString()")">
                <CreateFolder />
                <File Id="background.png" Source="install/images/background.png"/>
                <File Id="doodle.png" Source="install/images/doodle.png"/>
                <File Id="platform.png" Source="install/images/platform.png"/>
              </Component>
              <Component Id="DLLs" Guid="$(powershell -command "[guid]::NewGuid().ToString()")">
                <File Id="sfml_graphics.dll" Source="install/sfml-graphics-2.dll"/>
                <File Id="sfml_window.dll" Source="install/sfml-window-2.dll"/>
                <File Id="sfml_system.dll" Source="install/sfml-system-2.dll"/>
                <File Id="sfml_audio.dll" Source="install/sfml-audio-2.dll"/>
                <File Id="sfml_network.dll" Source="install/sfml-network-2.dll"/>
              </Component>
            </DirectoryRef>
            
            <Feature Id="MainFeature" Title="Main" Level="1">
              <ComponentRef Id="MainExecutable" />
              <ComponentRef Id="Images" />
              <ComponentRef Id="DLLs" />
            </Feature>
          </Product>
        </Wix>
        EOF

    - name: Compile WXS to MSI
      shell: bash
      run: |
        cd build
        candle.exe -nologo install.wxs -out install.wixobj
        light.exe -nologo install.wixobj -out packages/DoodleJump-1.0.0.msi -ext WixUIExtension

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-msi-package
        path: build/packages/
        retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Windows release includes:
          - MSI installer package
        draft: false
        prerelease: false
        files: |
          artifacts/windows-msi-package/*.msi
        token: ${{ secrets.GITHUB_TOKEN }}
